引入parrot url解析

diff --git a/rootfstool b/rootfstool
--- a/rootfstool
+++ b/rootfstool
@@ -16,15 +16,20 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #
+#########
+#2>/dev/null
+#########
 ROOTFSTOOL_VERSION="1.0"
 RGB_MAIN_COLOR="254;228;208"
 MAIN_COLOR="\033[1;38;2;${RGB_MAIN_COLOR}m"
 LXC_MIRROR_MAIN="http://images.linuxcontainers.org/images"
 LXC_MIRROR_BFSU="https://mirrors.bfsu.edu.cn/lxc-images/images"
+PARROTOS_MIRROR_MAIN="http://archive.parrotsec.org/parrot/iso"
+PARROTOS_MIRROR_BFSU="https://mirrors.bfsu.edu.cn/parrot/iso"
 function format_html() {
   # Format html to text and filter out valid information
   # Modified from tmoe
-  case ${LXC_MIRROR} in
+  case ${MIRROR} in
   "bfsu")
     echo "$*" | grep "href" | grep "title" | sed -E 's@<a (href)@\n\1@g' | awk -F 'href=' '{print $2}' | cut -d '"' -f 2 | cut -d "/" -f 1 | grep -v '\.\.' | grep -v "&amp;"
     ;;
@@ -34,12 +39,14 @@ function format_html() {
   esac
 }
 function select_mirror() {
-  case ${LXC_MIRROR} in
+  case ${MIRROR} in
   "bfsu")
-    export MIRROR=${LXC_MIRROR_BFSU}
+    export LXC_MIRROR=${LXC_MIRROR_BFSU}
+    export PARROTOS_MIRROR=${PARROTOS_MIRROR_BFSU}
     ;;
   "main" | "")
-    export MIRROR=${LXC_MIRROR_MAIN}
+    export LXC_MIRROR=${LXC_MIRROR_MAIN}
+    export PARROTOS_MIRROR=${PARROTOS_MIRROR_MAIN}
     ;;
   esac
 }
@@ -106,15 +113,15 @@ function get_cpu_arch() {
 }
 function list_lxc_distros() {
   # It will print the distro name if any version of distro is available for current ${CPU_ARCH}
-  # $LXC_MIRROR and $CPU_ARCH are defined at main()
+  # $MIRROR and $CPU_ARCH are defined at main()
   if [[ ${CPU_ARCH} == "" ]]; then
     get_cpu_arch
   fi
-  export LXC_MIRROR=${LXC_MIRROR}
+  export MIRROR=${MIRROR}
   select_mirror
-  for DISTRO in $(format_html $(curl -sL ${MIRROR})); do
-    for VERSION in $(format_html $(curl -sL ${MIRROR}/$DISTRO)); do
-      if [[ $(curl -sL ${MIRROR}/${DISTRO}/${VERSION}/${CPU_ARCH} | grep "404 Not Found") = "" ]]; then
+  for DISTRO in $(format_html $(curl -sL ${LXC_MIRROR})); do
+    for VERSION in $(format_html $(curl -sL ${LXC_MIRROR}/$DISTRO)); do
+      if [[ $(curl -sL ${LXC_MIRROR}/${DISTRO}/${VERSION}/${CPU_ARCH} | grep "404 Not Found") = "" ]]; then
         echo -e "${MAIN_COLOR}[${CPU_ARCH}] ${DISTRO}"
         break
       else
@@ -126,7 +133,11 @@ function list_lxc_distros() {
 }
 function list_distro_version() {
   # If the version of the distro is available, print it
-  # $LXC_MIRROR, $DISTRO and $CPU_ARCH are defined at main()
+  # $MIRROR, $DISTRO and $CPU_ARCH are defined at main()
+  if [[ ${DISTRO} == "parrot" ]]; then
+    list_parrotos_version
+    return 0
+  fi
   if [[ ${DISTRO} == "" ]]; then
     echo -e "\033[31mOS distro not set.\033[0m"
     exit 1
@@ -134,14 +145,32 @@ function list_distro_version() {
   if [[ ${CPU_ARCH} == "" ]]; then
     get_cpu_arch
   fi
-  export LXC_MIRROR=${LXC_MIRROR}
+  export MIRROR=${MIRROR}
   select_mirror
-  if [[ $(curl -sL ${MIRROR}/${DISTRO} | grep "404 Not Found") != "" ]]; then
+  if [[ $(curl -sL ${LXC_MIRROR}/${DISTRO} | grep "404 Not Found") != "" ]]; then
     echo -e "\033[31mOS distro not found.\033[0m"
     exit 1
   fi
-  for VERSION in $(format_html $(curl -sL ${MIRROR}/${DISTRO})); do
-    if [[ $(curl -sL ${MIRROR}/${DISTRO}/${VERSION}/${CPU_ARCH} | grep "404 Not Found") = "" ]]; then
+  for VERSION in $(format_html $(curl -sL ${LXC_MIRROR}/${DISTRO})); do
+    if [[ $(curl -sL ${LXC_MIRROR}/${DISTRO}/${VERSION}/${CPU_ARCH} | grep "404 Not Found") = "" ]]; then
+      VERSION_FOUND=1
+      echo -e "${MAIN_COLOR}[${CPU_ARCH}] ${DISTRO} : ${VERSION}"
+    fi
+  done
+  if [[ ${VERSION_FOUND} != 1 ]]; then
+    echo -e "\033[31mCould not found image for current cpu architecture.\033[0m"
+    exit 1
+  fi
+  printf "\033[0m"
+}
+function list_parrotos_version() {
+  if [[ ${CPU_ARCH} == "" ]]; then
+    get_cpu_arch
+  fi
+  export MIRROR=${MIRROR}
+  select_mirror
+  for VERSION in $(format_html $(curl -sL ${PARROTOS_MIRROR})); do
+    if [[ $(curl -sL ${PARROTOS_MIRROR}/${VERSION} | grep "tar.xz" | grep ${CPU_ARCH} | grep -v "torrent" | head -n 1) != "" ]]; then
       VERSION_FOUND=1
       echo -e "${MAIN_COLOR}[${CPU_ARCH}] ${DISTRO} : ${VERSION}"
     fi
@@ -154,24 +183,42 @@ function list_distro_version() {
 }
 function get_rootfs_url() {
   # Get rootfs download link of Specified $DISTRO and $VERSION
-  # $LXC_MIRROR, $DISTRO, $VERSION and $CPU_ARCH are defined at main()
+  # $MIRROR, $DISTRO, $VERSION and $CPU_ARCH are defined at main()
+  if [[ ${DISTRO} == "parrot" ]]; then
+    get_parrotos_url
+    return 0
+  fi
   if [[ ${CPU_ARCH} == "" ]]; then
     get_cpu_arch
   fi
-  export LXC_MIRROR=${LXC_MIRROR}
+  export MIRROR=${MIRROR}
   select_mirror
   if [[ ${DISTRO} = "gentoo" ]]; then
     VERSION2="openrc"
   else
     VERSION2="default"
   fi
-  TIME=$(format_html $(curl -sL ${MIRROR}/${DISTRO}/${VERSION}/${CPU_ARCH}/${VERSION2}) | tail -n1)
+  TIME=$(format_html $(curl -sL ${LXC_MIRROR}/${DISTRO}/${VERSION}/${CPU_ARCH}/${VERSION2}) | tail -n1)
   if [[ ${TIME} = "" ]]; then
     echo -e "\033[31mError: Can not find rootfs !\033[0m"
     exit 1
   fi
-  URL=${MIRROR}/${DISTRO}/${VERSION}/${CPU_ARCH}/${VERSION2}/${TIME}/rootfs.tar.xz
+  URL=${LXC_MIRROR}/${DISTRO}/${VERSION}/${CPU_ARCH}/${VERSION2}/${TIME}/rootfs.tar.xz
   echo ${URL}
+}
+function get_parrotos_url() {
+  if [[ ${CPU_ARCH} == "" ]]; then
+    get_cpu_arch
+  fi
+  export MIRROR=${MIRROR}
+  select_mirror
+  ROOTFS=$(format_html $(curl -sL ${PARROTOS_MIRROR}/${VERSION}) | grep "tar.xz" | grep ${CPU_ARCH} | grep -v "torrent" | head -n 1)
+  if [[ ${ROOTFS} == "" ]]; then
+    echo -e "\033[31mError: Can not find rootfs !\033[0m"
+    exit 1
+  fi
+  echo "${PARROTOS_MIRROR}/${VERSION}/${ROOTFS}"
+  echo "Note: you may need to repack the rootfs's \`parrot-${CPU_ARCH}/\` directory as \`./\` to make it to be a common rootfs." >&2
 }
 function exec_function() {
   # *Only for developer.
@@ -219,7 +266,7 @@ function main() {
       ;;
     "--mirror" | "-m")
       shift
-      export LXC_MIRROR=$1
+      export MIRROR=$1
       ;;
     esac
     shift
